version: 2

models:
  - name: mart_Local_Bike_Product_Sales
    description: "{{ doc('_mart_Local_Bike_Product_Sales') }}"
    columns:
      - name: customer_id
        description: Identifiant du client.

      - name: client_first_name
        description: Prénom du client.

      - name: client_last_name
        description: Nom du client.

      - name: order_id
        description: Identifiant de la commande.

      - name: order_date
        description: Date de la commande.

      - name: shipped_date
        description: Date d’expédition de la commande.

      - name: discounted_amount
        description: Montant total payé après remise.

      - name: product_id
        description: Identifiant du produit.

      - name: product_name
        description: Nom du produit.

      - name: brand_id
        description: Identifiant de la marque.

      - name: brand_name
        description: Nom de la marque.

      - name: category_id
        description: Identifiant de la catégorie du produit.

      - name: category_name
        description: Nom de la catégorie.

      - name: store_id
        description: Identifiant du magasin.

      - name: store_name
        description: Nom du magasin.

      - name: staff_first_name
        description: Prénom du vendeur.

      - name: staff_last_name
        description: Nom du vendeur.
