version: 2

sources:
  - name: Local_Bike
    schema: Local_Bike
    tables:
      - name: brands_raw
      - name: categories_raw
      - name: customers_raw
      - name: order_items_raw
      - name: order_raw
      - name: products_raw
      - name: staffs_raw
      - name: stocks_raw
      - name: stores_raw
